var annotated =
[
    [ "BrowserMainForm", "class_browser_main_form.html", "class_browser_main_form" ],
    [ "BrowserTab1", "class_browser_tab1.html", "class_browser_tab1" ],
    [ "BrowserTab2", "class_browser_tab2.html", "class_browser_tab2" ],
    [ "Cache", "class_cache.html", "class_cache" ],
    [ "Calculate", "class_calculate.html", "class_calculate" ],
    [ "CalculatorForm", "class_calculator_form.html", "class_calculator_form" ],
    [ "Cryptor", "class_cryptor.html", "class_cryptor" ],
    [ "decision_function", "structdecision__function.html", "structdecision__function" ],
    [ "FolderBrowser", "class_folder_browser.html", "class_folder_browser" ],
    [ "HideItApp", "class_hide_it_app.html", "class_hide_it_app" ],
    [ "HideItFormFactory", "class_hide_it_form_factory.html", "class_hide_it_form_factory" ],
    [ "HideItFrame", "class_hide_it_frame.html", "class_hide_it_frame" ],
    [ "HideItPanelFactory", "class_hide_it_panel_factory.html", "class_hide_it_panel_factory" ],
    [ "Kernel", "class_kernel.html", "class_kernel" ],
    [ "ListViewItemPopup", "class_list_view_item_popup.html", "class_list_view_item_popup" ],
    [ "ONE_CLASS_Q", "class_o_n_e___c_l_a_s_s___q.html", "class_o_n_e___c_l_a_s_s___q" ],
    [ "PopupEventListener", "class_popup_event_listener.html", "class_popup_event_listener" ],
    [ "PopupEventListenerTerminate", "class_popup_event_listener_terminate.html", "class_popup_event_listener_terminate" ],
    [ "ProxySensor", "class_proxy_sensor.html", "class_proxy_sensor" ],
    [ "QMatrix", "class_q_matrix.html", "class_q_matrix" ],
    [ "SceneRegister", "class_scene_register.html", "class_scene_register" ],
    [ "SettingPasswordForm", "class_setting_password_form.html", "class_setting_password_form" ],
    [ "ShowTerminatePopup", "class_show_terminate_popup.html", "class_show_terminate_popup" ],
    [ "Solver", "class_solver.html", "class_solver" ],
    [ "Solver_NU", "class_solver___n_u.html", "class_solver___n_u" ],
    [ "SVC_Q", "class_s_v_c___q.html", "class_s_v_c___q" ],
    [ "svm_model", "structsvm__model.html", "structsvm__model" ],
    [ "svm_node", "structsvm__node.html", "structsvm__node" ],
    [ "svm_parameter", "structsvm__parameter.html", "structsvm__parameter" ],
    [ "svm_problem", "structsvm__problem.html", "structsvm__problem" ],
    [ "SvmWrapper", "class_svm_wrapper.html", "class_svm_wrapper" ],
    [ "SVR_Q", "class_s_v_r___q.html", "class_s_v_r___q" ],
    [ "TextViewerForm", "class_text_viewer_form.html", "class_text_viewer_form" ]
];